# usage:
# python generate_marlin_small_table.py --csv autotune/marlin_tuning_best_configs.csv --out marlin_fp4/launch_config.py
# 
#
# Reads marlin_tuning_best_configs.csv and prints a compact nested dict:
#   MARLIN_FP4_TUNING = {
#     "NVIDIA GeForce RTX 5090": {
#        (M, K, N): (thread_k, thread_n, sms),
#        ...
#     },
#     ...
#   }
#
# Designed to be copy-pasted into your Marlin layer file.

import argparse
import csv
import os
from typing import Dict, Tuple


def _int(x):
    s = str(x).strip()
    return int(float(s))


def _load_existing_table(path: str) -> Dict[str, Dict[Tuple[int, int, int], Tuple[int, int, int]]]:
    """Best-effort load of MARLIN_FP4_TUNING from an existing output file."""
    if not path or not os.path.exists(path):
        return {}

    try:
        scope = {}
        with open(path, "r") as f:
            exec(f.read(), scope)
        existing = scope.get("MARLIN_FP4_TUNING", {})
        if isinstance(existing, dict):
            return existing
    except Exception:
        # If the file exists but is malformed, ignore and rebuild.
        pass
    return {}


def _merge_tables(base: Dict[str, Dict[Tuple[int, int, int], Tuple[int, int, int]]],
                  incoming: Dict[str, Dict[Tuple[int, int, int], Tuple[int, int, int]]]) -> Dict[str, Dict[Tuple[int, int, int], Tuple[int, int, int]]]:
    """Merge incoming tuning data into base, appending new/updated entries at the end."""
    merged: Dict[str, Dict[Tuple[int, int, int], Tuple[int, int, int]]] = {}

    # Start with existing entries to preserve their order.
    for dev, configs in base.items():
        merged[dev] = dict(configs)

    for dev, configs in incoming.items():
        current = merged.setdefault(dev, {})
        for key, value in configs.items():
            if key in current:
                # Move updated entry to the end.
                current.pop(key)
            current[key] = value
    return merged


def process(csv_path: str, out_path: str) -> None:
    # device_name -> (M,K,N) -> (tk,tn,sms)
    table: Dict[str, Dict[Tuple[int, int, int], Tuple[int, int, int]]] = {}

    with open(csv_path, "r", newline="") as f:
        r = csv.DictReader(f)
        for row in r:
            dev = str(row["gpu_name"]).strip()
            m = _int(row["m"])
            n = _int(row["n"])
            k = _int(row["k"])

            tk = _int(row["best_thread_k"])
            tn = _int(row["best_thread_n"])
            sms = _int(row["best_sms"])

            table.setdefault(dev, {})[(m, k, n)] = (tk, tn, sms)

    # Merge with any existing table from the output file so we preserve prior entries.
    existing_table = _load_existing_table(out_path)
    merged_table = _merge_tables(existing_table, table)

    # Emit compact python
    lines = []
    lines.append("# Auto-generated by generate_marlin_small_table.py")
    lines.append("# Copy-paste this into your Marlin layer file.\n")
    lines.append("MARLIN_FP4_TUNING = {")
    for dev, inner in merged_table.items():
        lines.append(f"  {dev!r}: {{")
        for (m, k, n), (tk, tn, sms) in inner.items():
            lines.append(f"    ({m}, {k}, {n}): ({tk}, {tn}, {sms}),")
        lines.append("  },")
    lines.append("}\n")


    text = "\n".join(lines)

    if out_path:
        with open(out_path, "w") as f:
            f.write(text)
        print(f"Wrote {out_path}")
    else:
        print(text)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", required=True, help="Path to marlin_tuning_best_configs.csv")
    ap.add_argument("--out", default="", help="Output file. If empty, print to stdout.")
    args = ap.parse_args()

    process(args.csv, args.out)


if __name__ == "__main__":
    main()
